	&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
	Matlab Code of VEA
	&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
	

	********************Initialization************************
	******************************************************
	hold on;k=100; x=2*rand(1,k)-0.06;y=2*rand(1,k)-0.03;max=-inf;min=inf;
	for i=1:k
	ob(i) = salomonfcn ([x(i) y(i)]);
	plot3(x(i),y(i), ob(i),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',1.5,...
	    'MarkerEdgeColor','b',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	m= salomonfcn ([x(i) y(i)]);
	  if(m>max)
	    max=m;
	     r1=i;
	  end
	  if(m<min)
	    min=m;
	     r2=i;
	  end
	end
	ob(r1),ob(r2)
	plot3(x(r1),y(r1), ob(r1),'--rs',...
	    'LineWidth',2,...
	

	******************** Initial Population*******************
	******************************************************
	hold on;ax=rand(1,k)+ x(r2);y=rand(1,k)+y(r2); 
	for i=1:k
	ob(i) = salomonfcn ([x(i) y(i)]);
	plot3(x(i),y(i), ob(i),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',1.5,...
	    'MarkerEdgeColor','b',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	m= salomonfcn ([x(i) y(i)]);
	  if(m>max)
	    max=m;
	     r1=i;
	  end
	  if(m<min)
	    min=m;
	     r2=i;
	  end
	end
	ob(r1),ob(r2)
	plot3(x(r1),y(r1), ob(r1),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',2,...
	    'MarkerEdgeColor','r',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	plot3(x(r2),y(r2), ob(r2),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',2,...
	    'MarkerEdgeColor','r',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	d=[x(r1)-x(r2), y(r1)-y(r2), ob(r1)-ob(r2)];
	ep=0.05;j=1; y1=0
	xn(j)= x(r1); yn(j)=y(r1); obn(j)= ob(r1);
	xn1(j)= x(r1)-ep*d(1); yn1(j)=y(r1)-ep*d(2); obn1(j)= ob(r1)-ep*d(3);
	    m1= salomonfcn ([xn1(j) yn1(j)]);m2= obn(j);
	plot3(xn1(j),yn1(j), obn1(j),'--rs',...
	    'LineWidth',3,...
	    'MarkerSize',3,...
	    'MarkerEdgeColor','black',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	w=j;
	while(m1<m2)
	        j=j+1; w=j-1;y1=1
	        xn(j)= xn(j-1)-ep*d(1); yn(j)=yn(j-1)-ep*d(2); obn(j)= obn(j-1)-ep*d(3);
	    m1= salomonfcn ([xn(j) yn(j)]);
	    m2= salomonfcn ([x(j-1) y(j-1)]);
	plot3(xn(j),yn(j), m1,'--rs',...
	    'LineWidth',3,...
	    'MarkerSize',3,...
	    'MarkerEdgeColor','black',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	end
	plot3(xn(w),yn(w), obn(w),'--rs',...
	    'LineWidth',3,...
	    'MarkerSize',3,...
	    'MarkerEdgeColor','r',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	
	p0 = [x(r2) y(r2) ob(r2)];
	p1 = [x(r1) y(r1) ob(r1)];
	vectarrow(p1,p0)
	
	hold on;ax=rand(1,k)+ x(r2);y=rand(1,k)+y(r2); 
	for i=1:k
	ob(i) = salomonfcn ([x(i) y(i)]);
	plot3(x(i),y(i), ob(i),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',1.5,...
	    'MarkerEdgeColor','b',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	m= salomonfcn ([x(i) y(i)]);
	  if(m>max)
	    max=m;
	     r1=i;
	  end
	  if(m<min)
	    min=m;
	     r2=i;
	  end
	end
	ob(r1),ob(r2)
	plot3(x(r1),y(r1), ob(r1),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',2,...
	    'MarkerEdgeColor','r',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	plot3(x(r2),y(r2), ob(r2),'--rs',...
	    'LineWidth',2,...
	    'MarkerSize',2,...
	    'MarkerEdgeColor','r',...
	    'MarkerFaceColor',[0.5,0.5,0.5])
	d=[x(r1)-x(r2), y(r1)-y(r2), ob(r1)-ob(r2)];
	ep=0.05;j=1; y1=0
	xn(j)= x(r1); yn(j)=y(r1); obn(j)= ob(r1);
	xn1(j)= x(r1)-ep*d(1); yn1(j)=y(r1)-ep*d(2); obn1(j)= ob(r1)-ep*d(3);
	    m1= salomonfcn ([xn1(j) yn1(j)]);m2= obn(j);
	plot3(xn1(j),yn1(j), obn1(j),'--rs',...
	    'LineWidth',3,...
	    'MarkerSize',3,...
hold on;p00 = [0 0 0];
vectarrow(p0,p00)
hold on;plot3(0,0,0,'--rs',...
    'LineWidth',5,...
    'MarkerSize',5,...
    'MarkerEdgeColor','black',...
    'MarkerFaceColor',[0.5,0.5,0.5])

