# -*- coding: utf-8 -*-
"""Results4_GA_PSO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKGWaqBorVn6sYDuRJfN9ckbnqwwiUOg
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.metrics import mean_squared_error
color_pal = sns.color_palette()

def print_metrics(y_test, y_pred,y_label, alg_name, dataset_name):

    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    print(f'RMSE Score on Test set: {rmse:.2f}')

    # Mean Absolute Error (MAE)
    mae = np.mean(np.abs(y_test - y_pred.reshape(y_pred.shape[0])))
    print(f'mae Score on Test set: {mae:.2f}')

    # R-squared (R2) Score
    mean_actual = np.mean(y_test)
    total_sum_of_squares = np.sum((y_test - mean_actual) ** 2)
    residual_sum_of_squares = np.sum((y_test - y_pred.reshape(y_pred.shape[0])) ** 2)
    r2 = 1 - (residual_sum_of_squares / total_sum_of_squares)
    print(f'r2 Score on Test set: {r2:.2f}')

    # Mean Bias Deviation (MBE):
    mbe = np.mean(y_test - y_pred.reshape(y_pred.shape[0]))
    print(f'mbe Score on Test set: {mbe:.2f}')

    # Median Absolute Error (MedAE):
    medae = np.median(np.abs(y_test - y_pred.reshape(y_pred.shape[0])))
    print(f'medae Score on Test set: {medae:.2f}')

    # Coefficient of Determination (COD):
    mean_actual = np.mean(y_test)
    total_sum_of_squares = np.sum((y_test - mean_actual) ** 2)
    residual_sum_of_squares = np.sum((y_test - y_pred.reshape(y_pred.shape[0])) ** 2)
    cod = 1 - (residual_sum_of_squares / total_sum_of_squares)
    print(f'cod Score on Test set: {cod:.2f}')

    # Explained Variance Score:
    explained_variance = 1 - (np.var(y_test - y_pred.reshape(y_pred.shape[0])) / np.var(y_test))
    print(f'explained_variance Score on Test set: {explained_variance:.2f}')

    # Relative Absolute Error (RAE):
    mae = np.mean(np.abs(y_test - y_pred.reshape(y_pred.shape[0])))
    baseline_mae = np.mean(np.abs(y_test - np.mean(y_test)))
    rae = mae / baseline_mae
    print(f'rae Score on Test set: {rae:.2f}')

    with open(f'./metrics-{alg_name}-{dataset_name}.txt','w') as f:
        txt = f"rmse: {rmse}"+'\n'+ f"mae: {mae}"+'\n'+f"r2: {r2}"+'\n'+f"medae: {medae}"+'\n'+f"cod: {cod}"+'\n'+f"explained_variance: {explained_variance}"+'\n'+f"rae: {rae}"+'\n'
        f.write(txt)

def plot_act_vs_pred(y_test, y_pred,y_label, alg_name, dataset_name):
    print_metrics(y_test, y_pred,y_label, alg_name, dataset_name)
    # Plot predictions vs. actual values
    plt.figure(figsize=(8, 3),)
    plt.plot(test.index, y_test, label='Actual', color='blue')
    plt.plot(test.index, y_pred, label='Predicted', color='red')
    plt.title(f'Actual vs. Predicted - {alg_name} - {dataset_name}')
    plt.xlabel('Date')
    plt.ylabel(y_label)
    plt.legend()
    plt.savefig(f"Actual vs. Predicted - {alg_name}' - {dataset_name}.png")
    plt.savefig(f"Actual vs. Predicted - {alg_name}' - {dataset_name}.svg", format='svg', dpi=1200, bbox_inches='tight', facecolor='white')
    plt.show()

dataset_name = 'pf_filled'
df = pd.read_csv(f'/content/drive/MyDrive/datasets (1)/time-series-forecasting/{dataset_name}.csv')
df = df.set_index('Time')
selected_column = df.columns[0]
df = df[selected_column]
df.index = pd.to_datetime(df.index)

df = df.to_frame()

df

df.columns

# df = df['prod_k28']

# df = df.loc[:, 'cons_k28']
# df = df.loc[:, 'prod_k28']

df

df.plot(style='.',
        figsize=(8, 3),
        color=color_pal[0],
        title=f'{dataset_name} Energy Use in KW')
plt.savefig(f"figure1-{dataset_name}.png")
plt.show()

# Split data to Train and Test

date = '09-01-2022'
train = df.loc[df.index < date]
test = df.loc[df.index >= date]

test

fig, ax = plt.subplots(figsize=(8, 3),)
train.plot(ax=ax, label='Training Set', title='Data Train/Test Split')
test.plot(ax=ax, label='Test Set')
ax.axvline(date, color='black', ls='--')
ax.legend(['Training Set', 'Test Set'])
plt.savefig(f"figure2-{dataset_name}.png")
plt.show()



start_of_week = '01-01-2022'
end_of_week = '01-08-2022'

df.loc[(df.index > start_of_week) & (df.index < end_of_week)] \
    .plot(figsize=(8, 3), title='Week Of Data')

plt.savefig(f"figure3-{dataset_name}.png")
plt.show()

df.index

df.index.dayofweek
print(df)

# df.columns

df

def create_features(df):
    """
    Create time series features based on time series index.
    """
    df = df.copy()
    df['hour'] = df.index.hour
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df


df = create_features(df)

df

dataset_name

fig, ax = plt.subplots(figsize=(8, 3),)
# sns.boxplot(data=df, x='hour', y='PJME_MW')
y_label = selected_column
sns.boxplot(data=df, x='hour', y=y_label)
ax.set_title('KW by Hour')
plt.savefig(f"figure4-{dataset_name}.png")
plt.show()

fig, ax = plt.subplots(figsize=(8, 3),)
# sns.boxplot(data=df, x='month', y='PJME_MW', palette='Blues')
sns.boxplot(data=df, x='month', y=y_label, palette='Blues')
ax.set_title('KW by Month')
plt.savefig(f"figure5-{dataset_name}.png")
plt.show()

train = create_features(train)
test = create_features(test)

FEATURES = ['dayofyear', 'hour', 'dayofweek', 'quarter', 'month', 'year']
# TARGET = 'PJME_MW'
TARGET = y_label

X_train = train[FEATURES]
y_train = train[TARGET]

X_test = test[FEATURES]
y_test = test[TARGET]

"""# XGboost"""

import xgboost as xgb

reg = xgb.XGBRegressor(base_score=0.5, booster='gbtree',
                       n_estimators=1000,
                       early_stopping_rounds=50,
                       objective='reg:linear',
                       max_depth=3,
                       learning_rate=0.01)
reg.fit(X_train, y_train,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        verbose=100)
y_pred = reg.predict(X_test)



plot_act_vs_pred(y_test, y_pred,y_label, 'XGBoot', dataset_name)

"""# DNN"""

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Build a deep neural network model using TensorFlow and Keras
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(6,)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
history = model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), verbose=1)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Visualize the training loss and validation loss over epochs
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

plot_act_vs_pred(y_test, y_pred,y_label, 'DNN', dataset_name)

"""# DNN Parameter Tuning using GA:"""

!pip install deap

!pip install pyswarm

no_optimizatin_epochs = 10
evaluation_epochs = 10
ga_population_size = 10
ga_ngen = 10
pso_swarm_size = 10
pso_maxiter = 10
best_model_pso_epochs = 100

import random
import numpy as np
from deap import base, creator, tools, algorithms
import tensorflow as tf
from tensorflow import keras

# Define the fitness function
nfe = 0
def evaluate(individual):
    global nfe
    nfe += 1
    print(nfe)
    individual[0] = int(individual[0])
    individual[1] = int(individual[1])
    print('first layer: ', individual[0])
    print('second layer: ', individual[1])
    # Define the architecture of the neural network based on the individual's genes
    model = keras.Sequential()
    # print('**** Shape: ', X_train.shape)
    model.add(keras.layers.Dense(int(individual[0]), activation='relu', input_shape=(X_train.shape[1],)))
    model.add(keras.layers.Dense(int(individual[1]), activation='relu'))
    model.add(keras.layers.Dense(1))

    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error')

    # Train and evaluate the model
    history = model.fit(X_train, y_train, epochs=evaluation_epochs, validation_data=(X_test, y_test), verbose=0)
    loss = history.history['val_loss'][-1]

    return (loss,)

# Create a fitness function maximizing minimization
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

# Create a toolbox for GA
toolbox_ga = base.Toolbox()
toolbox_ga.register("attr_int", random.randint, 16, 128)  # For the number of neurons in layers
toolbox_ga.register("individual", tools.initRepeat, creator.Individual, toolbox_ga.attr_int, n=2)
toolbox_ga.register("population", tools.initRepeat, list, toolbox_ga.individual)

toolbox_ga.register("evaluate", evaluate)
toolbox_ga.register("mate", tools.cxTwoPoint)
toolbox_ga.register("mutate", tools.mutUniformInt, low=16, up=128, indpb=0.2)
toolbox_ga.register("select", tools.selTournament, tournsize=3)

# Define your X_train and Y_train datasets here

# Create the initial GA population
ga_population = toolbox_ga.population(n=ga_population_size)

# Run the genetic algorithm
algorithms.eaSimple(ga_population, toolbox_ga, cxpb=0.7, mutpb=0.2, ngen=ga_ngen, verbose=True)

# Get the best individual from the GA population
best_individual_ga = tools.selBest(ga_population, k=1)[0]

# Create a PSO population with the best GA individual as the initial particle
from pyswarm import pso

def pso_optimization(individual):
    loss = evaluate(individual)[0]
    return loss

# Convert the GA individual to a PSO-friendly format (list of integers)
best_individual_pso = [int(best_individual_ga[0]), int(best_individual_ga[1])]

# Define the bounds for PSO
lb = [16, 16]
ub = [128, 128]

# Run PSO with the best GA individual as the initial particle
x_opt, f_opt = pso(pso_optimization, lb, ub, swarmsize=pso_swarm_size, maxiter=pso_maxiter)

# Print the results
print("Best architecture found by PSO:", x_opt)
print("Best architecture found by PSO (rounded):", [int(x_opt[0]), int(x_opt[1])])

# Train and evaluate the best model with the architecture found by PSO
best_model_pso = keras.Sequential()
best_model_pso.add(keras.layers.Dense(int(x_opt[0]), activation='relu', input_shape=(X_train.shape[1],)))
best_model_pso.add(keras.layers.Dense(int(x_opt[1]), activation='relu'))
best_model_pso.add(keras.layers.Dense(1))
best_model_pso.compile(optimizer='adam', loss='mean_squared_error')

history2 = best_model_pso.fit(X_train, y_train, epochs=best_model_pso_epochs, verbose=1, validation_data=(X_test, y_test))
test_loss = best_model_pso.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss}")

# Make predictions
y_pred = best_model_pso.predict(X_test)

plot_act_vs_pred(y_test, y_pred,y_label, 'DNN-GA-PSO', dataset_name)